import React from 'react';
import { Check, X, AlertTriangle, ShieldCheck } from 'lucide-react';

export default function Approvals() {
  return (
    <div className="max-w-5xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-text-primary">Approvals</h1>
        <p className="mt-2 text-text-secondary">Review and authorize AI-generated automations before they are executed.</p>
      </div>

      <div className="bg-surface rounded-xl shadow-sm border border-border">
        <div className="p-6 border-b border-border bg-surface-secondary rounded-t-xl flex items-center justify-between">
          <div className="flex items-center gap-2 text-text-primary font-semibold">
            <ShieldCheck className="w-5 h-5 text-info" />
            Pending Authorization (1)
          </div>
        </div>

        <div className="p-6 space-y-6">
          <div className="flex justify-between items-start">
            <div>
              <h2 className="text-xl font-bold text-text-primary">Invoice Processing Flow</h2>
              <p className="text-sm text-text-secondary mt-1">Generated by WorkTwin AI on Aug 23, 2026</p>
            </div>
            <span className="px-3 py-1 bg-warning/20 text-warning rounded-full text-xs font-semibold flex items-center gap-1">
              <AlertTriangle className="w-3 h-3" /> Requires Human Review
            </span>
          </div>

          <div className="bg-surface-secondary border border-border rounded-lg p-4 space-y-3">
            <h3 className="font-semibold text-text-primary text-sm">Requested Permissions:</h3>
            <ul className="space-y-2 text-sm text-text-secondary">
              <li className="flex items-center gap-2"><Check className="w-4 h-4 text-success" /> Read access to specific email folder (Invoices)</li>
              <li className="flex items-center gap-2"><Check className="w-4 h-4 text-success" /> API access to Accounting System (POST /invoices)</li>
              <li className="flex items-center gap-2"><Check className="w-4 h-4 text-success" /> Local filesystem access (Downloads folder)</li>
            </ul>
          </div>

          <div className="border-t border-border pt-6 flex justify-end gap-4">
            <button className="px-6 py-2.5 border border-border text-text-primary rounded-lg font-medium hover:bg-surface-secondary transition-colors flex items-center gap-2">
              <X className="w-4 h-4" /> Reject Plan
            </button>
            <button className="px-6 py-2.5 bg-accent hover:bg-accent-hover text-white rounded-lg font-medium transition-colors flex items-center gap-2 shadow-sm">
              <Check className="w-4 h-4" /> Approve & Execute
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
